# Generated by Django 3.2.9 on 2024-03-07 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Ttj/staff')),
                ('amount_of_existance', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('room_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ttj.room')),
                ('capacity', models.IntegerField(default=4)),
                ('status', models.IntegerField(blank=True, null=True, verbose_name=((0, 'Joy qolmagan'), (1, 'Foydalanishga berilmagan'), (2, "Bo'sh"), (3, "Bo'sh joylar bor")))),
            ],
            bases=('ttj.room',),
        ),
        migrations.CreateModel(
            name='Ttj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='Ttj/Images')),
                ('location', models.CharField(max_length=250)),
                ('location_link', models.CharField(max_length=250)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomStuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttj.room')),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttj.stuff')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='ttj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttj.ttj'),
        ),
    ]
