# Generated by Django 3.2.9 on 2024-03-07 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('ttj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.customuser')),
                ('image', models.ImageField(upload_to='Staff/Images')),
                ('position', models.IntegerField(choices=[(0, 'Mudir'), (1, 'Qorovul'), (2, 'Hamshira'), (3, 'Tarbiyachi'), (4, 'Farrosh')], default=2)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Maoshni UZS da kiriting', max_digits=15)),
            ],
            options={
                'ordering': ['first_name', 'date_joined'],
            },
            bases=('account.customuser',),
        ),
    ]
