# Generated by Django 4.2.11 on 2024-03-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttj', '0005_alter_stuff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttj',
            name='capacity',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
