# Generated by Django 4.2.11 on 2024-03-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttj', '0006_ttj_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
