# Generated by Django 4.2.11 on 2024-03-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttj', '0007_staff_is_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, upload_to='Staff/Images'),
        ),
    ]
