# Generated by Django 4.2.11 on 2024-04-22 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttj', '0010_alter_bed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='ttj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ttj.ttj'),
        ),
    ]
