# Generated by Django 4.2.11 on 2024-04-22 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttj', '0011_staff_ttj'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='ttj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ttj.ttj'),
        ),
    ]
