# Generated by Django 4.2.11 on 2024-03-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.customuser')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Studen/Image')),
                ('group', models.CharField(max_length=50)),
                ('study_type', models.IntegerField(choices=[(0, 'Sirtqi'), (1, 'Ananaviy')], default=1)),
                ('smena', models.IntegerField(choices=[(0, '1-smena'), (1, '2-smena'), (2, 'Kechgi smena')], default=0)),
                ('status', models.IntegerField(blank=True, null=True, verbose_name=((0, "Qora Ro'yxatda"), (1, '1-guruh nogironi'), (2, 'Yoshlar dafarida turadi'), (3, 'Chin yetim')))),
                ('approved', models.BooleanField(default=False)),
                ('qr_code_data', models.CharField(blank=True, max_length=150, null=True)),
                ('qr_code_file', models.ImageField(upload_to='Student/Qr_code')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.faculty')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
            options={
                'verbose_name_plural': ['Students'],
                'ordering': ['date_joined'],
            },
            bases=('account.customuser',),
        ),
    ]
