# Generated by Django 3.2.9 on 2024-03-07 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_blacklist'),
        ('ttj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='ttj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttj.ttj'),
        ),
    ]
