# Generated by Django 3.2.9 on 2024-03-07 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttj', '0001_initial'),
        ('student', '0004_blacklist_ttj'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Chiqdi'), (1, 'Kirdi')], default=1)),
                ('tracked_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('ttj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttj.ttj')),
            ],
            options={
                'ordering': ['-tracked_at'],
            },
        ),
    ]
