# Generated by Django 4.2.11 on 2024-03-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='smena',
            field=models.IntegerField(blank=True, choices=[(0, '1-smena'), (1, '2-smena'), (2, 'Kechgi smena')]),
        ),
    ]
