# Generated by Django 4.2.11 on 2024-03-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_smena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, "Qora Ro'yxatda"), (1, '1-guruh nogironi'), (2, 'Yoshlar dafarida turadi'), (3, 'Chin yetim')], null=True),
        ),
    ]
