# Generated by Django 4.2.11 on 2024-03-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_student_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['date_joined'], 'verbose_name_plural': 'Studentlar'},
        ),
    ]
