# Generated by Django 4.2.11 on 2024-03-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, "TTJ ga joylashtirish so'rovi rad etildi"), (1, "Ko'rib chiqilmoqda"), (2, 'TTJ ga qabul qilindi')], default=1),
        ),
    ]
