# Generated by Django 4.2.11 on 2024-03-08 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptance', models.IntegerField(choices=[(0, 'Rad etildi'), (1, 'Qabul qilindi')], default=0)),
                ('description', models.TextField()),
                ('last_review_time', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.booking')),
            ],
        ),
    ]
