# Generated by Django 4.2.11 on 2024-03-18 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_bookingreviewer'),
        ('student', '0012_bookingreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='university.university'),
        ),
    ]
