# Generated by Django 4.2.11 on 2024-04-29 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttj', '0013_staff_visible_password'),
        ('student', '0013_booking_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ttj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ttj.ttj'),
        ),
    ]
