# Generated by Django 4.2.11 on 2024-05-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_payment_ttj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='smena',
            field=models.IntegerField(choices=[(0, '1-smena'), (1, '2-smena'), (2, 'Kechgi smena')], default=0),
        ),
    ]
