# Generated by Django 4.2.11 on 2024-05-03 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_alter_student_smena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='smena',
            field=models.IntegerField(choices=[(0, '1-smena'), (1, '2-smena'), (2, 'Kechgi smena')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_type',
            field=models.IntegerField(choices=[(0, 'Sirtqi'), (1, 'Ananaviy')], default=1, null=True),
        ),
    ]
