# Generated by Django 4.2.11 on 2024-05-08 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_bookingreviewer_options_alter_faculty_options_and_more'),
        ('student', '0016_alter_student_smena_alter_student_study_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklist',
            options={'ordering': ['created_at'], 'verbose_name_plural': "Qora ro'yxat"},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_at'], 'verbose_name': "Yotoqxonada turish so'rovi", 'verbose_name_plural': "Yotoqxonada turish so'rovlari"},
        ),
        migrations.AlterModelOptions(
            name='bookingreview',
            options={'verbose_name': "Ko'rib chiqilgan so'rov", 'verbose_name_plural': "Ko'rib chiqilgan so'rovlar"},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': "To'lovlar"},
        ),
        migrations.AlterModelOptions(
            name='studenttracking',
            options={'ordering': ['-tracked_at'], 'verbose_name_plural': 'Student Kirdi Chiqdisi'},
        ),
        migrations.AlterField(
            model_name='student',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Qanul qilindi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Balansi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.faculty', verbose_name='Facultet'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=50, verbose_name='Guruh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, "Qora Ro'yxatda"), (1, '1-guruh nogironi'), (2, 'Yoshlar dafarida turadi'), (3, 'Chin yetim')], null=True, verbose_name='Ijtimioy holati'),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_type',
            field=models.IntegerField(choices=[(0, 'Sirtqi'), (1, 'Ananaviy')], default=1, null=True, verbose_name="O'qish turi"),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university', verbose_name='Universitet'),
        ),
    ]
