# Generated by Django 4.2.11 on 2024-03-15 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingReviewer',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.customuser')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('is_working', models.BooleanField(default=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university')),
            ],
            options={
                'abstract': False,
            },
            bases=('account.customuser',),
        ),
    ]
