# Generated by Django 4.2.11 on 2024-03-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_bookingreviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingreviewer',
            name='visible_password',
            field=models.CharField(max_length=150, null=True, verbose_name='PassWord'),
        ),
    ]
